version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: GestorAlumnosDb
    ports:
      - "5432:5432"  # Asegúrate de que el puerto 5432 esté expuesto
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistencia de datos
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
