version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: GestorAlumnosDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d # Aquí metes tu dump.sql
    networks:
      - pg_network

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "8082:8080"  # puerto libre para Adminer
    networks:
      - pg_network

  webapplication1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp_container
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=dpg-d3bgfk3uibrs73felch0-a.oregon-postgres.render.com;Port=5432;Database=gestoralumnosdb;Username=admin;Password=eshHKRRf02FFSWx9DTIq4EGKJvzjagAb;SSL Mode=Require;Trust Server Certificate=true"
    ports:
      - "5000:80" # Render asigna 80 o 8080, aquí puedes mapear a 5000 en local
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
